### ISSUE TITLE
Is justinrainbow/json-schema absolutely required?

### ISSUE THREAD

**Issue by Bilge** [ergebnis/json-normalizer#147]
Is it possible to drop the dependency on `justinrainbow/json-schema`? My project is locked at version 2.0 of this library, and consequently, we cannot use `localheinz/composer-normalize`. Alternatively, can support be extended back to version 2.0?

If it is only required by `SchemaNormalizer`, perhaps it can be moved to a suggested dependency instead, and code be added to `SchemaNormalizer` to check if the library is available and emit an exception if it is not. In this way, consumers that do not want `SchemaNormalizer` do not need to load the dependency on `justinrainbow/json-schema`. It seems to me `localheinz/composer-normalize` is one such library that does not actually use `SchemaNormalizer` in the current version.

**Comment by localheinz** [comment]
@Bilge 

Actually, `SchemaNormalizer` is the core of `localheinz/composer-normalize`!
